# -*- coding: utf-8 -*-
"""API Call Sequence

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gsVd5TS5LZUB6nD2XI3FHAHrrLCdUfGF
"""

import json
import pandas as pd

# Show Row Data
with open("ApiCall-Gandcrab.txt") as data_apicall : 
  counter = 0
  report_log = []

  for api in data_apicall: 
    report_log.append(api)
    
  df_report_log = pd.DataFrame(report_log)
  df_report_log.to_csv('reportLog.csv')

df_report_log

from google.colab import drive
drive.mount('/content/drive')

list = []

with open("ApiCall-Gandcrab.txt") as data_apicall : 

  for api in data_apicall: 
    data_split = api.split('\t')
    data_split.pop(5)
    
    
    dict = {"timestamp" : data_split[0],"process" : data_split[1],"pid" : data_split[2],"tid" : data_split[3],"type" : data_split[4], "value" : data_split[5],}

    # df = pd.DataFrame(dict)
    # df.to_csv('sample.csv')
    list.append(dict)
    
  print(list)

df = pd.DataFrame(list)

df.to_csv("apicall.csv")

df

df_value = df['value']

import re

list_value = []
list_argument = []
i = 0
for value in df_value:
  split_value = value.split('(', 1)
  list_value.append(split_value[0])
  list_argument.append(split_value[1])
  
  # split_value[1] = re.sub(".$", '', split_value[1])
  # split_argument = split_value[0].split('(')
  # split_value_0 = split_value[0].split('(')
  # split_value_0 = re.sub(".$", '', split_value)

  # print(split_argument)
  
  # dict = {'apicall' : split_value[0], 'argument' : split_value[1:]}

  # list_value.append(dict)

test_dct = {
    'value' : list_value,
    'argument' : list_argument
}

df_test = pd.DataFrame(test_dct)
# df_test.head()
df_test

"""
  pertama
  for i in argument
  baru
  if else check jumlah argument
  create column
  assign column
  
"""

argument_splited = []
ko = 0
for i in test_dct['argument']:
  splited = i.split(',')
  argument_splited.append(splited)
  # print(splited)
  # if len(splited)>1:
  #   print(splited[1])
  # if ko==20:
  #   break
  # ko += 1

for i in argument_splited:
  print("panjangnya data =   " + str(len(i)))

print(argument_splited)

test_dct1 = {}


test_dct1['argument1'] = []
test_dct1['argument2'] = []
test_dct1['argument3'] = []
test_dct1['argument4'] = []
test_dct1['argument5'] = []
test_dct1['argument6'] = []

print(argument_splited[5])
print(argument_splited[5][0])
# for i in argument_splited:
#   print(i[0])

for i in argument_splited:
  test_dct1['argument1'].append(i[0])
  if len(i)>1:
    test_dct1['argument2'].append(i[1])
  else:
    test_dct1['argument2'].append('none')
  if len(i)>2:
    test_dct1['argument3'].append(i[2])
  else:
    test_dct1['argument3'].append('none')
  if len(i)>3:
    test_dct1['argument4'].append(i[3])
  else:
    test_dct1['argument4'].append('none')
  if len(i)>4:
    test_dct1['argument5'].append(i[4])
  else:
    test_dct1['argument5'].append('none')
  if len(i)>5:
    test_dct1['argument6'].append(i[5])
  else:
    test_dct1['argument6'].append('none')

df_coba = pd.DataFrame(test_dct1)
df_coba.to_csv('argumen_split.csv')
df_coba

print(dict)

df_value_csv = pd.DataFrame(list_value)

df_value_csv.to_csv('value.csv')

df_value_csv

list_value = []
list_argument = []

for value in df_value: 
  value = re.sub(".$", '', value)
  split_value = value.split('(')
  split_argument = split_value[1].split(',')

  # print(split_argument)
  
  # dict = {'apicall' : split_value[0], 'argument' : split_value[1]}

  # list_value.append(dict)
  res = {idx: ele for idx, ele in enumerate(split_argument)}
  
  list_argument.append(str(res))

df_list_argument = pd.DataFrame(list_argument)

df_list_argument.to_csv('list_argument.csv')

df_list_argument

