# -*- coding: utf-8 -*-
"""API Call Sequence

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gsVd5TS5LZUB6nD2XI3FHAHrrLCdUfGF
"""

import json
import pandas as pd

with open("ApiCall-Gandcrab.txt") as data_apicall : 
  counter = 0

  for api in data_apicall: 
    if(counter <= 5):
      print(api)
      counter+=1

list = []

with open("ApiCall-Gandcrab.txt") as data_apicall : 

  for api in data_apicall: 
    data_split = api.split('\t')
    data_split.pop(5)
    
    
    dict = {"timestamp" : data_split[0],"process" : data_split[1],"pid" : data_split[2],"tid" : data_split[3],"type" : data_split[4], "value" : data_split[5],}

    # df = pd.DataFrame(dict)
    # df.to_csv('sample.csv')
    list.append(dict)
    
  print(list)

df = pd.DataFrame(list)

df.to_csv("apicall.csv")

df.head()

df_value = df['value']

import re

list_value = []
for value in df_value: 
  value = re.sub(".$", '', value)
  split_value = value.split('(')
  dict = {'apicall' : split_value[0], 'argument' : split_value[1]}

  list_value.append(dict)

df_value_csv = pd.DataFrame(list_value)

df_value_csv.to_csv('value.csv')

df_value_csv.head(10)

